CREATE TABLE capstone1_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    affirmation_id INTEGER
        REFERENCES capstone1_affirmations(id) ON DELETE CASCADE NOT NULL,
    author_id INTEGER
        REFERENCES capstone1_users(id) ON DELETE CASCADE NOT NULL
);